// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggdazdzgopinvgdtoqrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZGF6ZHpnb3BpbnZnZHRvcXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDI0NzAsImV4cCI6MjA2NzExODQ3MH0.27PGeX7aT3rsHmue0WcySTaRtd-PLsFAGKKCy8c4szU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});